# Generated by Django 3.1 on 2020-08-06 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200806_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='finish_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 8, 6)),
        ),
    ]
