# Generated by Django 3.1 on 2020-08-07 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('LA', 'Language'), ('FR', 'Framework')], default='LA', max_length=5)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 8, 7)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 8, 7)),
        ),
    ]
