# Generated by Django 3.1 on 2020-08-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200807_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(choices=[('LANGUAGE', 'Language'), ('FRAMEWORK', 'Framework')], default='LANGUAGE', max_length=15),
        ),
    ]
