# Generated by Django 3.1 on 2020-08-08 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200807_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 8, 8)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 8, 8)),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(choices=[('LANGUAGE', 'Language'), ('FRAMEWORK', 'Framework'), ('VERSION CONTROL', 'vc')], default='LANGUAGE', max_length=15),
        ),
    ]
