# Generated by Django 3.1 on 2020-08-09 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20200808_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 8, 9)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 8, 9)),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(choices=[('LANGUAGE', 'La'), ('FRAMEWORK', 'Fr'), ('VERSION CONTROL', 'Vc')], default='LANGUAGE', max_length=15),
        ),
    ]
